# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Taha Iqbal
title: Senior Java, Integration and Cloud Engineer
email: taha@iqbalt.com
website: www.iqbalt.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: tahaiqbalkhan9
github_username:  tahaiqbalkhan9
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: tiqbal9
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: iqbalt.com
  icon: fas fa-globe
  url: https://www.iqbalt.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Taha Iqbal and I'm a Senior Backend Developer. As well as Backend development, I also have experience in AWS Cloud, Middleware ESBs(Mulesoft and Talend) and Microservices(Rest APIs). I have worked at a number of companies gaining teamwork and leadership skills. 

  I can gather ,analyse and consolidate information into a set of requirements by iterative architecture design approach in consultation with stakeholders which fits into an organisation's technical landscape.

  I have also helped organisations modernise their core & legacy solutions using latest available technologies including Cloud.

  I am most skilled in: <mark>Backend Development</mark>, <mark>Integration</mark> and <mark>DevOps</mark>.

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Datacom
        link: https://datacom.com/
        link_text: www.datacom.com
        sub_title: Senior Developer
        caption: Apr 2022 - Present
        quote: >
          Incredibly proud to be working for New Zealand National Postal service and making difference in lives of Kiwis. Helping NZ Post replacing/retiring core and legacy applications with available latest technologies using Cloud first strategy
        description: | # this will include new lines to allow paragraphs
            Working in Te Iho project to enhance NZ Post parcel sortation capabilities using latest available technologies.
            Integration APIs design using `Lucid Chart`, `BPMN`, `RAML` and `Mule CloudHub Exchange`.

            Integration APIs implementation/development by leveraging *Mulesoft API Led Connectivity* architecture pattern using `Anypoint Studio 7`, `MuleSoft 4`, `Mule CloudHub Runtime`, `FTP/SFTP`, `AWS EC2`, `S3` and `MSSQL Server` Database. 

            Helping NZ Post Mule developers to upgrade Mule API deployment processes using `CI` and `CD pipelines` using `Azure DevOps`, `Maven` and `CloudHub`.

            On-going Production Support of critical Mule APIs and issue resolution.

      - layout: left
        border: weak
        title: Bank of New Zealand
        link: https://www.bnz.co.nz/
        link_text: www.bnz.co.nz
        sub_title: DevOps Engineer
        caption: Apr 2020 - Apr 2022 - 2yrs 1mo
        quote: >
          Helped BNZ internal Customers by producing solutions that are secure and solves critical problem
        description: | # this will include new lines to allow paragraphs
            Deployed, 24x7 Support and Monitored Enterprise Applications having critical up-time requirement using `AWS CloudFormation`, `AWS Lambda`, `Hashicorp Terraform`, `Jenkins Pipeline`, `Redhat Ansible`, `CI/CD`, `Python`, `PowerShell` and `Bash`.

            Conducted `AWS Cloud Security Infrastructure remediation` on projects `AWS Accounts` based on `CSAM Security Assessment` guidelines.

            Uplifted BNZ Finance and Procure to Pay(P2P) department capability by Integrating [SAP](https://www.sap.com/) system to [Coupa Procurement System(SaaS)](https://www.coupa.com/). Delivered an Integration Solution that synchronises critical datasets such as Purchase Orders, Invoices and related Assets using `Mulesoft 4`, `Anypoint Studio 7`, `Restful APIs`, `SAP BAPIs`, `Python`, `Openshift`, and `Unix scripting`.

      - layout: left
        border: weak
        title: OSS Group Ltd
        link: https://www.oss-group.co.nz/
        link_text: www.oss-group.co.nz
        sub_title: Software Architect
        caption: Jul 2016 - Apr 2020 - 3yrs 10mos
        quote: >
          Great Clients, awesome Team and mentors makes it breeze to solve business problems
        description: | # this will include new lines to allow paragraphs
            Rolled out latest `Talend` Middleware to replace existing legacy Middlware solution in Tower Insurance.
            Worked as an Integration Architect to design and deliver end to end Data Migration and Integration Solution for Tower Insurance using `Talend` Middleware. 
            Developed `data pipelines` to migrate and/or synchorinse data from on-prem `MSSQL` Databases to `Datalake` established using `Cloudera Enterprise Platform`.
            
            Delivered middle-ware Integration Project for Mitre10 that provides integration between customer data and retail data for a Marketing SaaS, using `Mulesoft 3.8.2`, `Rabbit MQ` and `MySQL`. Project scope was to integrate with Marketing product from various data sources including `FTP`, `SFTP`, `Amazon S3`, `RabbitMQ`, `MySQL`, `XML/CSV/JSON/SOAP` and `Rest APIs`.
            
            Rolled out `Kong API Gateway` for SKY TV. Conducted *workshops, training of product, user, product guides/docs*, integrate existing `microservices applications` with `Kong API Gateway`.

            Successfully delivered Integration Solution between Student Management System(SMS) and [Canvas Learning Management System(LMS)](https://www.instructure.com/en-au/canvas) for [MIT(Manukau Institute of Technology)](https://www.manukau.ac.nz/).
            
            `R` language for Data Analysis and `Apache NiFi` for Data logistics.

      - layout: left
        border: weak
        title: Folio3 Software
        link: https://www.folio3.com/
        link_text: www.folio3.com
        sub_title: Lead Software Engineer
        caption: Jul 2015 - May 2016 - 11mos
        quote: >
          Leadership responsibilities and mentoring of Junior developers
        description: | # this will include new lines to allow paragraphs
            Developed Intelligent Automation Chatbot project (Qlue, later acquired by ServiceNow) using `Java 8`, `Dropwizard 0.9.2`, `Jetty` and `PostgreSQL`. Used `Jenkins` for `CI/CD` using `Docker Containers`. Worked on Integration of project with [Salesforce CRM](https://www.salesforce.com).

            Produced comprehensive "deployment automation strategy" for `Micro services` using `shell scripting`, `Docker`, `Gradle`, `Git` and `Jenkins`.

            *Line management duties, interviews, training and mentoring of junior developers*.

            Support for ongoing `Java` projects.

      - layout: left
        border: weak
        title: Folio3 Software
        link: https://www.folio3.com/
        link_text: www.folio3.com
        sub_title: Senior Software Engineer
        caption: Jan 2014 - Jul 2015 - 1yr 7mos
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Led the team of Backend Java developers that delivered automation of Business process of Feed yard Log management system for Zoetis. Designed `Restful web service architecture(SOA)` using `Apache CXF`, `Spring 3.0`, `Jackson`, `JSON`, `AngularJS` and `MySQL`.

            Developed several modules of Log management project including integration with external system(s), `Database modelling`, `Security` and Integrity of web services and project delivery.

      - layout: left
        border: weak
        title: Folio3 Software
        link: https://www.folio3.com/
        link_text: www.folio3.com
        sub_title: Software Engineer
        caption: Nov 2012 - Jan 2014 - 1yr 3mos
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Worked on "Consumer Portal" developed using `Java 7`, `Spring 3.0.2`, `Struts 2`, `MySql/SQL Server`, `Hibernate`. Reporting using `Jasper reports`.

            Hands on experience in designing UI/UX using `HTML`, `CSS`, `Jquery 2.x`, `Ajax`, `JSP` and `Velocity` templates. 

            Researched various issues day in and day out to find the best solution needed. 

      - layout: left
        border: weak
        title: Systems Limited
        link: https://www.systemsltd.com/
        link_text: www.systemsltd.com
        sub_title: Software Engineer
        caption: May 2012 - Oct 2012 - 6mos
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Managed and supported legacy codebase written in `Java 6`, `JBoss`, `JSF`, `RichFaces4`, `MSSQLServer` and `SVN`.
            Business Reporting using `Eclipse BIRT Tool`.

      - layout: left
        border: weak
        title: Kalsoft
        link: https://kalsoft.com/
        link_text: kalsoft.com
        sub_title: Software Engineer
        caption: Feb 2011 - May 2012 - 1yr 4mos
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Worked as a developer on `SaaS` `SOA Architecture` to expose Restful web services to Mobile and browser clients using `Apache CXF`, `Spring MVC`, `MySQ`L, `SVN` and `Apache Tomcat`.
            
            Implementation of business logic, efficient code writing practices and design patterns.
            
            Database development using `MySQL`.           

      - layout: left
        border: weak
        title: VectraCom
        link: https://vectracom.com/
        link_text: vectracom.com
        sub_title: Intern
        caption: Sep 2011 - Nov 2012 - 3mos
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            Worked as a researcher for the Industry University Collaboration Programme for Natural Language Processing project.
            Researched on Morphological Analyser for Natural Language. Conversion of row Natural Language data to formatted XML using `Python scripting`.             

  - title: Certifications 
    layout: text 
    border: weak
    content: | 
      - *(In Progress) MuleSoft Certified Integration Architect - Level 1*
      - MuleSoft Certified Developer - Level 1(Mule 4)
      - ICAgile Certified Professional
      - AWS Certified Cloud Practitioner (CLF)  
      - AWS Technical Professional Digital
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Karachi
        caption: 2007 - 2010
        sub_title: BS Computer Science
        quote: >
          Programming, Networking courses and Sports(why not!)
        description: | # this will include new lines to allow paragraphs
          Graduated with majors in <mark>Software Engineering</mark>. Courses include <mark>Data structures</mark>, <mark>Programming</mark>, <mark>System analysis and design</mark>, <mark>Linear Algebra</mark> and <mark>Statistical methods</mark>.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming and software engineering some of my other interests and hobbies are:
      - Hiking
      - Table Tennis
      - Figuring out [if Earth's actually flat?](https://www.youtube.com/watch?v=VNqNnUJVcVs)
      - Enjoying day trips in beautiful New Zealand

      Look at this cool image  
      ![Nature](/images/IMG_6688.jpeg "Nature")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
